"""create all tables

Revision ID: 4a8b5b81217b
Revises: 
Create Date: 2026-06-27 18:22:52.481749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a8b5b81217b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_events_created_at'), 'app_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_events_event_type'), 'app_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_app_events_id'), 'app_events', ['id'], unique=False)
    op.create_index('ix_app_events_type_created_at', 'app_events', ['event_type', 'created_at'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('final_cash', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_created_at'), 'backtests', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtests_id'), 'backtests', ['id'], unique=False)
    op.create_index('ix_backtests_strategy_created_at', 'backtests', ['strategy_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_backtests_symbol_id'), 'backtests', ['symbol_id'], unique=False)
    op.create_index('ix_backtests_symbol_strategy', 'backtests', ['symbol_id', 'strategy_name'], unique=False)
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'opened_at', name='uq_bars_symbol_timeframe_opened_at')
    )
    op.create_index(op.f('ix_bars_id'), 'bars', ['id'], unique=False)
    op.create_index(op.f('ix_bars_symbol_id'), 'bars', ['symbol_id'], unique=False)
    op.create_index('ix_bars_symbol_timeframe_opened_at', 'bars', ['symbol_id', 'timeframe', 'opened_at'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', name='uq_positions_symbol_id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_symbol_id'), 'positions', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_positions_updated_at'), 'positions', ['updated_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index('ix_signals_strategy_created_at', 'signals', ['strategy_name', 'created_at'], unique=False)
    op.create_index('ix_signals_symbol_created_at', 'signals', ['symbol_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_signals_symbol_id'), 'signals', ['symbol_id'], unique=False)
    op.create_table('llm_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('memo_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_memos_created_at'), 'llm_memos', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_memos_id'), 'llm_memos', ['id'], unique=False)
    op.create_index('ix_llm_memos_signal_created_at', 'llm_memos', ['signal_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_memos_signal_id'), 'llm_memos', ['signal_id'], unique=False)
    op.create_index('ix_llm_memos_type_created_at', 'llm_memos', ['memo_type', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_signal_id'), 'orders', ['signal_id'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('ix_orders_symbol_created_at', 'orders', ['symbol_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_symbol_id'), 'orders', ['symbol_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_position_size', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_created_at'), 'risk_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_decisions_id'), 'risk_decisions', ['id'], unique=False)
    op.create_index('ix_risk_decisions_signal_created_at', 'risk_decisions', ['signal_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_risk_decisions_signal_id'), 'risk_decisions', ['signal_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_filled_at'), 'fills', ['filled_at'], unique=False)
    op.create_index(op.f('ix_fills_id'), 'fills', ['id'], unique=False)
    op.create_index('ix_fills_order_filled_at', 'fills', ['order_id', 'filled_at'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index('ix_fills_order_filled_at', table_name='fills')
    op.drop_index(op.f('ix_fills_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_filled_at'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_risk_decisions_signal_id'), table_name='risk_decisions')
    op.drop_index('ix_risk_decisions_signal_created_at', table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_created_at'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_orders_symbol_id'), table_name='orders')
    op.drop_index('ix_orders_symbol_created_at', table_name='orders')
    op.drop_index('ix_orders_status_created_at', table_name='orders')
    op.drop_index(op.f('ix_orders_signal_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_llm_memos_type_created_at', table_name='llm_memos')
    op.drop_index(op.f('ix_llm_memos_signal_id'), table_name='llm_memos')
    op.drop_index('ix_llm_memos_signal_created_at', table_name='llm_memos')
    op.drop_index(op.f('ix_llm_memos_id'), table_name='llm_memos')
    op.drop_index(op.f('ix_llm_memos_created_at'), table_name='llm_memos')
    op.drop_table('llm_memos')
    op.drop_index(op.f('ix_signals_symbol_id'), table_name='signals')
    op.drop_index('ix_signals_symbol_created_at', table_name='signals')
    op.drop_index('ix_signals_strategy_created_at', table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_positions_updated_at'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_bars_symbol_timeframe_opened_at', table_name='bars')
    op.drop_index(op.f('ix_bars_symbol_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_id'), table_name='bars')
    op.drop_table('bars')
    op.drop_index('ix_backtests_symbol_strategy', table_name='backtests')
    op.drop_index(op.f('ix_backtests_symbol_id'), table_name='backtests')
    op.drop_index('ix_backtests_strategy_created_at', table_name='backtests')
    op.drop_index(op.f('ix_backtests_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_created_at'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_app_events_type_created_at', table_name='app_events')
    op.drop_index(op.f('ix_app_events_id'), table_name='app_events')
    op.drop_index(op.f('ix_app_events_event_type'), table_name='app_events')
    op.drop_index(op.f('ix_app_events_created_at'), table_name='app_events')
    op.drop_table('app_events')
    # ### end Alembic commands ###
