"""add signal persistence fields

Revision ID: bbd4adb18257
Revises: ee59a3b1f23c
Create Date: 2026-06-30 18:37:12.978017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd4adb18257'
down_revision: Union[str, Sequence[str], None] = 'ee59a3b1f23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('timeframe', sa.String(length=16), nullable=False))
    op.add_column('signals', sa.Column('reason', sa.Text(), nullable=False))
    op.add_column('signals', sa.Column('bar_timestamp', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'bar_timestamp')
    op.drop_column('signals', 'reason')
    op.drop_column('signals', 'timeframe')
    # ### end Alembic commands ###
