"""add source to bars

Revision ID: ee59a3b1f23c
Revises: 4a8b5b81217b
Create Date: 2026-06-28 16:42:27.320023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee59a3b1f23c'
down_revision: Union[str, Sequence[str], None] = '4a8b5b81217b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bars', sa.Column('source', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('uq_bars_symbol_timeframe_opened_at'), 'bars', type_='unique')
    op.create_unique_constraint('uq_bars_symbol_timeframe_opened_at_source', 'bars', ['symbol_id', 'timeframe', 'opened_at', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bars_symbol_timeframe_opened_at_source', 'bars', type_='unique')
    op.create_unique_constraint(op.f('uq_bars_symbol_timeframe_opened_at'), 'bars', ['symbol_id', 'timeframe', 'opened_at'], postgresql_nulls_not_distinct=False)
    op.drop_column('bars', 'source')
    # ### end Alembic commands ###
